project_id = "iqdvawizxjglkdjyvhdr"

[functions.send-recovery-email]
verify_jwt = false

[functions.reset-redirect]
verify_jwt = false

[functions.validate-consultor]
verify_jwt = false

[functions.chat-ademicon]
verify_jwt = true

[functions.create-support-ticket]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true